################################# Default configuration ###################
#################################baseURL = "https://demo.gethugothemes.com/meghna/examplesite/"
baseURL = "https://www.silubra.com"
title = "Silubra Research"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
#[[params.plugins.css]]
#link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About Us"
url = "#about-us"
weight = 1

[[Languages.en.menu.main]]
name = "Services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "Partnerts"
url = "#partners"
weight = 3

[[Languages.en.menu.main]]
name = "Contact Us"
url = "#contact"
weight = 4


################### Turkish Navigation ########################
[[Languages.tr.menu.main]]
name = "Hakkımızda"
url = "#about-us"
weight = 1

[[Languages.tr.menu.main]]
name = "Hizmetlerimiz"
url = "#services"
weight = 2

[[Languages.tr.menu.main]]
name = "İş Ortaklarımız"
url = "#partners"
weight = 3

[[Languages.tr.menu.main]]
name = "İletişim"
url = "#contact"
weight = 4

############################# Default Parameters ##########################
[params]
logo = "images/silubralogo.png"
# Meta data
description = "Silubra Research Company Site"
author = "Silubra"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = false

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2023 Designed by Silubra Research"

################################ France Language ########################
[Languages.tr]
languageName = "Tr"
languageCode = "tr-tr"
contentDir = "content/Turkish"
weight = 2
home = "Ana Sayfa"
copyright = "Copyright &copy; 2023 Designed by Silubra Research"
